from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()



# # Definindo a base de dados de alimentos com informações nutricionais

# alimentos = [
#     # Frutas
#     {
#         "nome": "Abacate",
#         "categoria": "frutas",
#         "calorias": 96,
#         "proteinas": 1.2,
#         "lipidios": 8.4,
#         "colesterol": 0,
#         "carboidratos": 6,
#     },
#     {
#         "nome": "Banana",
#         "categoria": "frutas",
#         "calorias": 89,
#         "proteinas": 1.1,
#         "lipidios": 0.3,
#         "colesterol": 0,
#         "carboidratos": 23,
#     },
#     {
#         "nome": "Maçã",
#         "categoria": "frutas",
#         "calorias": 52,
#         "proteinas": 0.3,
#         "lipidios": 0.2,
#         "colesterol": 0,
#         "carboidratos": 14,
#     },
#     {
#         "nome": "Laranja",
#         "categoria": "frutas",
#         "calorias": 47,
#         "proteinas": 0.9,
#         "lipidios": 0.1,
#         "colesterol": 0,
#         "carboidratos": 12,
#     },
#     {
#         "nome": "Morango",
#         "categoria": "frutas",
#         "calorias": 32,
#         "proteinas": 0.7,
#         "lipidios": 0.3,
#         "colesterol": 0,
#         "carboidratos": 8,
#     },
#     # Cereais
#     {
#         "nome": "Arroz",
#         "categoria": "cereais",
#         "calorias": 130,
#         "proteinas": 2.7,
#         "lipidios": 0.3,
#         "colesterol": 0,
#         "carboidratos": 28,
#     },
#     {
#         "nome": "Aveia",
#         "categoria": "cereais",
#         "calorias": 389,
#         "proteinas": 16.9,
#         "lipidios": 6.9,
#         "colesterol": 0,
#         "carboidratos": 66,
#     },
#     {
#         "nome": "Quinoa",
#         "categoria": "cereais",
#         "calorias": 368,
#         "proteinas": 14.1,
#         "lipidios": 6.1,
#         "colesterol": 0,
#         "carboidratos": 64,
#     },
#     {
#         "nome": "Milho",
#         "categoria": "cereais",
#         "calorias": 86,
#         "proteinas": 3.2,
#         "lipidios": 1.2,
#         "colesterol": 0,
#         "carboidratos": 19,
#     },
#     {
#         "nome": "Centeio",
#         "categoria": "cereais",
#         "calorias": 335,
#         "proteinas": 10.3,
#         "lipidios": 2.5,
#         "colesterol": 0,
#         "carboidratos": 72,
#     },
#     # Verduras
#     {
#         "nome": "Couve",
#         "categoria": "verduras",
#         "calorias": 43,
#         "proteinas": 2.9,
#         "lipidios": 0.9,
#         "colesterol": 0,
#         "carboidratos": 9,
#     },
#     {
#         "nome": "Alface",
#         "categoria": "verduras",
#         "calorias": 15,
#         "proteinas": 1.4,
#         "lipidios": 0.2,
#         "colesterol": 0,
#         "carboidratos": 3,
#     },
#     {
#         "nome": "Espinafre",
#         "categoria": "verduras",
#         "calorias": 23,
#         "proteinas": 2.9,
#         "lipidios": 0.4,
#         "colesterol": 0,
#         "carboidratos": 3.6,
#     },
#     {
#         "nome": "Brócolis",
#         "categoria": "verduras",
#         "calorias": 34,
#         "proteinas": 2.8,
#         "lipidios": 0.4,
#         "colesterol": 0,
#         "carboidratos": 7,
#     },
#     {
#         "nome": "Cenoura",
#         "categoria": "verduras",
#         "calorias": 41,
#         "proteinas": 0.9,
#         "lipidios": 0.2,
#         "colesterol": 0,
#         "carboidratos": 10,
#     },
#     {
#         "nome": "Pimentão",
#         "categoria": "verduras",
#         "calorias": 20,
#         "proteinas": 0.9,
#         "lipidios": 0.1,
#         "colesterol": 0,
#         "carboidratos": 4.6,
#     },
#     # Carnes
#     {
#         "nome": "Frango",
#         "categoria": "carnes",
#         "calorias": 239,
#         "proteinas": 27.3,
#         "lipidios": 13.6,
#         "colesterol": 85,
#         "carboidratos": 0,
#     },
#     {
#         "nome": "Carne bovina",
#         "categoria": "carnes",
#         "calorias": 250,
#         "proteinas": 26.0,
#         "lipidios": 15.0,
#         "colesterol": 70,
#         "carboidratos": 0,
#     },
#     {
#         "nome": "Porco",
#         "categoria": "carnes",
#         "calorias": 242,
#         "proteinas": 25.7,
#         "lipidios": 14.0,
#         "colesterol": 82,
#         "carboidratos": 0,
#     },
#     {
#         "nome": "Peixe",
#         "categoria": "carnes",
#         "calorias": 206,
#         "proteinas": 22.0,
#         "lipidios": 12.0,
#         "colesterol": 63,
#         "carboidratos": 0,
#     },
#     {
#         "nome": "Peru",
#         "categoria": "carnes",
#         "calorias": 189,
#         "proteinas": 28.0,
#         "lipidios": 7.0,
#         "colesterol": 82,
#         "carboidratos": 0,
#     },
#     {
#         "nome": "Carneiro",
#         "categoria": "carnes",
#         "calorias": 294,
#         "proteinas": 25.0,
#         "lipidios": 21.0,
#         "colesterol": 97,
#         "carboidratos": 0,
#     },
#     # Derivados do leite
#     {
#         "nome": "Leite",
#         "categoria": "derivados do leite",
#         "calorias": 42,
#         "proteinas": 3.4,
#         "lipidios": 1.0,
#         "colesterol": 5,
#         "carboidratos": 5,
#     },
#     {
#         "nome": "Queijo",
#         "categoria": "derivados do leite",
#         "calorias": 402,
#         "proteinas": 25.0,
#         "lipidios": 33.0,
#         "colesterol": 105,
#         "carboidratos": 1.3,
#     },
#     {
#         "nome": "Iogurte",
#         "categoria": "derivados do leite",
#         "calorias": 59,
#         "proteinas": 10.0,
#         "lipidios": 0.4,
#         "colesterol": 5,
#         "carboidratos": 3.6,
#     },
#     {
#         "nome": "Manteiga",
#         "categoria": "derivados do leite",
#         "calorias": 717,
#         "proteinas": 0.9,
#         "lipidios": 81.0,
#         "colesterol": 215,
#         "carboidratos": 0,
#     },
#     {
#         "nome": "Creme de leite",
#         "categoria": "derivados do leite",
#         "calorias": 340,
#         "proteinas": 2.8,
#         "lipidios": 36.0,
#         "colesterol": 130,
#         "carboidratos": 2.9,
#     },
#     {
#         "nome": "Ricota",
#         "categoria": "derivados do leite",
#         "calorias": 174,
#         "proteinas": 11.3,
#         "lipidios": 13.0,
#         "colesterol": 49,
#         "carboidratos": 3.8,
#     },
#     # Miscelâneas
#     {
#         "nome": "Chocolate amargo",
#         "categoria": "miscelâneas",
#         "calorias": 546,
#         "proteinas": 6.5,
#         "lipidios": 31.3,
#         "colesterol": 5,
#         "carboidratos": 61,
#     },
#     {
#         "nome": "Mel",
#         "categoria": "miscelâneas",
#         "calorias": 304,
#         "proteinas": 0.3,
#         "lipidios": 0,
#         "colesterol": 0,
#         "carboidratos": 82,
#     },
#     {
#         "nome": "Molho de soja",
#         "categoria": "miscelâneas",
#         "calorias": 53,
#         "proteinas": 8.1,
#         "lipidios": 0.1,
#         "colesterol": 0,
#         "carboidratos": 4.9,
#     },
#     {
#         "nome": "Geleia",
#         "categoria": "miscelâneas",
#         "calorias": 250,
#         "proteinas": 0.4,
#         "lipidios": 0,
#         "colesterol": 0,
#         "carboidratos": 65,
#     },
#     {
#         "nome": "Ketchup",
#         "categoria": "miscelâneas",
#         "calorias": 112,
#         "proteinas": 1.2,
#         "lipidios": 0.2,
#         "colesterol": 0,
#         "carboidratos": 26,
#     },
#     # Alimentos preparados
#     {
#         "nome": "Pizza",
#         "categoria": "alimentos preparados",
#         "calorias": 266,
#         "proteinas": 11.0,
#         "lipidios": 10.0,
#         "colesterol": 17,
#         "carboidratos": 33,
#     },
#     {
#         "nome": "Hambúrguer",
#         "categoria": "alimentos preparados",
#         "calorias": 295,
#         "proteinas": 17.0,
#         "lipidios": 14.0,
#         "colesterol": 40,
#         "carboidratos": 31,
#     },
#     {
#         "nome": "Sopa de legumes",
#         "categoria": "alimentos preparados",
#         "calorias": 50,
#         "proteinas": 2.0,
#         "lipidios": 1.5,
#         "colesterol": 0,
#         "carboidratos": 8,
#     },
#     {
#         "nome": "Lasanha",
#         "categoria": "alimentos preparados",
#         "calorias": 135,
#         "proteinas": 6.0,
#         "lipidios": 4.0,
#         "colesterol": 16,
#         "carboidratos": 16,
#     },
#     {
#         "nome": "Macarrão",
#         "categoria": "alimentos preparados",
#         "calorias": 157,
#         "proteinas": 5.0,
#         "lipidios": 1.0,
#         "colesterol": 22,
#         "carboidratos": 30,
#     },
#     # Leguminosas
#     {
#         "nome": "Feijão",
#         "categoria": "leguminosas",
#         "calorias": 127,
#         "proteinas": 8.7,
#         "lipidios": 0.5,
#         "colesterol": 0,
#         "carboidratos": 23,
#     },
#     {
#         "nome": "Lentilha",
#         "categoria": "leguminosas",
#         "calorias": 116,
#         "proteinas": 9.0,
#         "lipidios": 0.4,
#         "colesterol": 0,
#         "carboidratos": 20,
#     },
#     {
#         "nome": "Grão-de-bico",
#         "categoria": "leguminosas",
#         "calorias": 164,
#         "proteinas": 8.9,
#         "lipidios": 2.6,
#         "colesterol": 0,
#         "carboidratos": 27,
#     },
#     {
#         "nome": "Ervilha",
#         "categoria": "leguminosas",
#         "calorias": 81,
#         "proteinas": 5.4,
#         "lipidios": 0.4,
#         "colesterol": 0,
#         "carboidratos": 14,
#     },
#     {
#         "nome": "Soja",
#         "categoria": "leguminosas",
#         "calorias": 173,
#         "proteinas": 16.6,
#         "lipidios": 9.0,
#         "colesterol": 0,
#         "carboidratos": 9.9,
#     },
#     # Nozes
#     {
#         "nome": "Amêndoas",
#         "categoria": "nozes",
#         "calorias": 579,
#         "proteinas": 21.2,
#         "lipidios": 49.9,
#         "colesterol": 0,
#         "carboidratos": 21.6,
#     },
#     {
#         "nome": "Nozes",
#         "categoria": "nozes",
#         "calorias": 654,
#         "proteinas": 15.2,
#         "lipidios": 65.2,
#         "colesterol": 0,
#         "carboidratos": 13.7,
#     },
#     {
#         "nome": "Castanha-do-Pará",
#         "categoria": "nozes",
#         "calorias": 656,
#         "proteinas": 14.3,
#         "lipidios": 66.4,
#         "colesterol": 0,
#         "carboidratos": 12.3,
#     },
#     {
#         "nome": "Avelã",
#         "categoria": "nozes",
#         "calorias": 628,
#         "proteinas": 14.9,
#         "lipidios": 60.8,
#         "colesterol": 0,
#         "carboidratos": 16.7,
#     },
#     {
#         "nome": "Macadâmia",
#         "categoria": "nozes",
#         "calorias": 718,
#         "proteinas": 7.9,
#         "lipidios": 75.8,
#         "colesterol": 0,
#         "carboidratos": 13.8,
#     },
# ]
